Repository 9oormthon-univ/2024_DANPOONG_TEAM_13_BE, pull requests merged in 2024-12, with the labels that each got.

#186 🔨 Refactor/#185 - 게시판에 기간 추가, 기간에 따른 스케줄링 로직 추가 및 Response 변경
  src/main/java/com/daon/onjung/account/domain/Store.java
  src/main/java/com/daon/onjung/core/listener/AppEventListener.java
  src/main/java/com/daon/onjung/core/listener/SchedulerRecoveryListener.java
  src/main/java/com/daon/onjung/event/application/controller/consumer/EventSchedulerConsumerV1Controller.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/BoardSchedulerConsumerV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/CommentConsumerV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/LikeConsumerV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/CreateCommentResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardDetailResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardOverviewResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadCommentOverviewResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateBoardService.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateCommentService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ProcessCompletedBoardService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardDetailService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardOverviewService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadCommentOverviewService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/ProcessCompletedBoardUseCase.java
  src/main/java/com/daon/onjung/suggestion/domain/mysql/Board.java
  src/main/java/com/daon/onjung/suggestion/domain/mysql/Comment.java
  src/main/java/com/daon/onjung/suggestion/domain/mysql/Like.java
  src/main/java/com/daon/onjung/suggestion/domain/redis/ScheduledBoardJob.java
  src/main/java/com/daon/onjung/suggestion/domain/service/BoardService.java
  src/main/java/com/daon/onjung/suggestion/domain/service/CommentService.java
  src/main/java/com/daon/onjung/suggestion/domain/service/LikeService.java
  src/main/java/com/daon/onjung/suggestion/domain/service/ScheduledBoardJobService.java
  src/main/java/com/daon/onjung/suggestion/domain/type/.keep
  src/main/java/com/daon/onjung/suggestion/domain/type/EStatus.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/BoardRepository.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/CommentRepository.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/LikeRepository.java
  src/main/java/com/daon/onjung/suggestion/repository/redis/ScheduledBoardJobRepository.java
Labels: 🔨 Refactor, dongkyeomjang

#193 🔨 Refactor/#192 - 길찾기를 위한 Store에 위경도 추가, 가게 상세조회 Response 변경
  http/DummyHttpRequest.http
  src/main/java/com/daon/onjung/account/application/dto/response/ReadStoreDetailResponseDto.java
  src/main/java/com/daon/onjung/account/domain/Store.java
  src/main/java/com/daon/onjung/account/domain/service/StoreService.java
  src/main/java/com/daon/onjung/security/application/dto/request/SignUpOwnerByDefaultRequestDto.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
Labels: 🔨 Refactor, dongkyeomjang

#195 🐞 BugFix/#194 - 댓글 작성자가 글 작성자로 표시되던 버그 수정 #194
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadCommentOverviewResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateBoardService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadCommentOverviewService.java
Labels: 🐞 BugFix, dongkyeomjang

#199 🐞 BugFix/#196 - 게시글 Overview 조회에서 글자수 오타로 발생하는 버그 수정
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardOverviewResponseDto.java
Labels: 🐞 BugFix, dongkyeomjang

#197 🔨 Refactor/#188 - 이벤트 데이터 조회 쿼리 최적화
  build.gradle
  config/prometheus.yml
  src/main/java/com/daon/onjung/core/constant/Constants.java
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
  src/main/java/com/daon/onjung/event/repository/mysql/EventRepository.java
Labels: 🔨 Refactor

#200 🔨 Refactor/#198 - QR 중앙 이미지 제거
  src/main/java/com/daon/onjung/core/utility/QrUtil.java
Labels: 🔨 Refactor, bianbbc87

#202 🐞 BugFix/#201 - Container TimeZone 설정 오류로, UTC 기반의 시간을 JVM이 사용하고 있던 버그 수정
  .github/workflows/dev-cicd.yml
Labels: 🐞 BugFix, dongkyeomjang
