Repository 9oormthon-univ/2024_DANPOONG_TEAM_13_BE, pull requests merged in 2024-11, with the labels that each got.

#14 ✅Test/#10: add AuthControllerHttpRequest
  http/auth/AuthControllerHttpRequest.http
Labels: ✅ Test, dongkyeomjang

#17 🔨Refactor/#15: del not used import
  src/main/java/com/daon/onjung/account/domain/Store.java
  src/main/java/com/daon/onjung/account/domain/service/OwnerService.java
  src/main/java/com/daon/onjung/security/application/controller/AuthController.java
  src/main/java/com/daon/onjung/security/application/dto/response/DefaultJsonWebTokenDto.java
  src/main/java/com/daon/onjung/security/application/service/AuthenticateJsonWebTokenService.java
  src/main/java/com/daon/onjung/security/application/service/AuthenticateOauthService.java
  src/main/java/com/daon/onjung/security/application/service/LoginOwnerByDefaultService.java
  src/main/java/com/daon/onjung/security/application/service/LoginUserByOauthService.java
  src/main/java/com/daon/onjung/security/application/service/ReadOrCreateUserService.java
  src/main/java/com/daon/onjung/security/application/service/ReissueJsonWebTokenService.java
  src/main/java/com/daon/onjung/security/handler/common/AbstractFailureHandler.java
Labels: 🔨 Refactor, dongkyeomjang

#19 📃Docs/#18: add http-client.private.env.json on .gitignore
  .gitignore
Labels: 📃 Docs, dongkyeomjang

#21 🌏 Deploy - CICD Pipeline 구축
  .github/workflows/dev-cicd.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
Labels: 🌏 Deploy, dongkyeomjang

#23 📃Docs/#22: AuthControllerHttpRequest 오타 수정
  http/auth/AuthControllerHttpRequest.http
Labels: 📃 Docs, dongkyeomjang

#31 ✨Feature/#24: 4.1 전체 온기 통계 조회 API 구현
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/onjung/application/controller/command/.keep
  src/main/java/com/daon/onjung/onjung/application/controller/query/OnjungQueryV1Controller.java
  src/main/java/com/daon/onjung/onjung/application/dto/request/.keep
  src/main/java/com/daon/onjung/onjung/application/dto/response/ReadOnjungSummaryResponseDto.java
  src/main/java/com/daon/onjung/onjung/application/service/.keep
  src/main/java/com/daon/onjung/onjung/application/service/ReadOnjungSummaryService.java
  src/main/java/com/daon/onjung/onjung/application/usecase/.keep
  src/main/java/com/daon/onjung/onjung/application/usecase/ReadOnjungSummaryUseCase.java
  src/main/java/com/daon/onjung/onjung/domain/Onjung.java
  src/main/java/com/daon/onjung/onjung/domain/application/controller/.keep
  src/main/java/com/daon/onjung/onjung/domain/application/dto/.keep
  src/main/java/com/daon/onjung/onjung/domain/application/service/.keep
  src/main/java/com/daon/onjung/onjung/domain/application/usecase/.keep
  src/main/java/com/daon/onjung/onjung/domain/service/DonationService.java
  src/main/java/com/daon/onjung/onjung/domain/service/OnjungService.java
  src/main/java/com/daon/onjung/onjung/domain/service/ReceiptService.java
  src/main/java/com/daon/onjung/onjung/domain/service/ShareService.java
  src/main/java/com/daon/onjung/onjung/repository/mysql/DonationRepository.java
  src/main/java/com/daon/onjung/onjung/repository/mysql/ReceiptRepository.java
  src/main/java/com/daon/onjung/onjung/repository/mysql/ShareRepository.java
Labels: ✨ Feature, dongkyeomjang

#35 🔨 Refactor/#34: User의 온기 총 횟수 계산 로직에서 가게별 중복 제거
  src/main/java/com/daon/onjung/onjung/application/service/ReadOnjungBriefService.java
  src/main/java/com/daon/onjung/onjung/application/service/ReadOnjungCountService.java
  src/main/java/com/daon/onjung/onjung/domain/service/OnjungService.java
Labels: 🔨 Refactor, dongkyeomjang

#36 ✨ Feature/#27 - 4.4 가게 방문 인증용 영수증 OCR 조회하기 API 구현
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/dto/ReceiptOCRDto.java
  src/main/java/com/daon/onjung/core/exception/error/ErrorCode.java
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/core/utility/OCRUtil.java
  src/main/java/com/daon/onjung/core/utility/RestClientUtil.java
  src/main/java/com/daon/onjung/onjung/application/controller/command/.keep
  src/main/java/com/daon/onjung/onjung/application/controller/command/OnjungCommandV1Controller.java
  src/main/java/com/daon/onjung/onjung/application/dto/response/ReceiptOCRResponseDto.java
  src/main/java/com/daon/onjung/onjung/application/service/ReceiptOCRService.java
  src/main/java/com/daon/onjung/onjung/application/usecase/ReceiptOCRUseCase.java
Labels: ✨ Feature, dongkyeomjang

#37 ✨ Feature/#28 - 4.5 영수증 리뷰 등록하기 API 구현
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
  src/main/java/com/daon/onjung/core/exception/error/ErrorCode.java
  src/main/java/com/daon/onjung/onjung/application/controller/command/OnjungCommandV1Controller.java
  src/main/java/com/daon/onjung/onjung/application/dto/request/.keep
  src/main/java/com/daon/onjung/onjung/application/dto/request/CreateReceiptRequestDto.java
  src/main/java/com/daon/onjung/onjung/application/service/CreateReceiptService.java
  src/main/java/com/daon/onjung/onjung/application/usecase/CreateReceiptUseCase.java
  src/main/java/com/daon/onjung/onjung/domain/service/ReceiptService.java
Labels: ✨ Feature, dongkyeomjang

#40 🐞 BugFix - 로그인 KakaoAccountDto 맵핑 오류 해결
  src/main/java/com/daon/onjung/security/info/KakaoOauth2UserInfo.java
Labels: 🐞 BugFix, dongkyeomjang

#41 ✨ Feature/#30 - 4.7 가게 후원 동참하기 API 구현
  http/auth/AuthControllerHttpRequest.http
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
  src/main/java/com/daon/onjung/account/repository/mysql/UserRepository.java
  src/main/java/com/daon/onjung/core/dto/CreateVirtualAccountResponseDto.java
  src/main/java/com/daon/onjung/core/dto/DepositOrTransferVirtualAccountResponseDto.java
  src/main/java/com/daon/onjung/core/dto/ReadVirtualAccountResponseDto.java
  src/main/java/com/daon/onjung/core/utility/BankUtil.java
  src/main/java/com/daon/onjung/core/utility/RestClientUtil.java
  src/main/java/com/daon/onjung/event/domain/Event.java
  src/main/java/com/daon/onjung/event/domain/service/EventService.java
  src/main/java/com/daon/onjung/event/repository/mysql/EventRepository.java
  src/main/java/com/daon/onjung/onjung/application/controller/command/OnjungCommandV1Controller.java
  src/main/java/com/daon/onjung/onjung/application/dto/request/CreateDonationRequestDto.java
  src/main/java/com/daon/onjung/onjung/application/dto/response/CreateDonationResponseDto.java
  src/main/java/com/daon/onjung/onjung/application/dto/response/ReceiptOCRResponseDto.java
  src/main/java/com/daon/onjung/onjung/application/service/CreateDonationService.java
  src/main/java/com/daon/onjung/onjung/application/service/ReceiptOCRService.java
  src/main/java/com/daon/onjung/onjung/application/usecase/CreateDonationUseCase.java
  src/main/java/com/daon/onjung/onjung/domain/service/DonationService.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
  src/main/java/com/daon/onjung/security/config/SuperUserConfig.java
Labels: ✨ Feature, dongkyeomjang

#42 ✨Feature/#7 - 3.1 가게 리스트 조회 API 구현
  build.gradle
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/controller/query/StoreQueryV1Controller.java
  src/main/java/com/daon/onjung/account/application/dto/response/ReadStoreOverviewsResponseDto.java
  src/main/java/com/daon/onjung/account/application/service/ReadStoreOverviewService.java
  src/main/java/com/daon/onjung/account/application/usecase/ReadStoreOverviewUseCase.java
  src/main/java/com/daon/onjung/account/domain/Store.java
  src/main/java/com/daon/onjung/account/domain/service/StoreService.java
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
Labels: ✨ Feature, bianbbc87

#45 🔨 refactor/#44 : build.gradle --parameter 제거
  build.gradle
Labels: 🔨 Refactor, bianbbc87

#47 ✨ Feature/#8 3.2 가게 상세 정보 조회 API 구현
  build.gradle
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/controller/query/StoreQueryV1Controller.java
  src/main/java/com/daon/onjung/account/application/dto/response/ReadStoreDetailResponseDto.java
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
  src/main/java/com/daon/onjung/account/application/usecase/ReadStoreDetailUseCase.java
  src/main/java/com/daon/onjung/account/domain/StoreHistory.java
  src/main/java/com/daon/onjung/account/repository/mysql/StoreHistoryRepository.java
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/core/utility/RestClientUtil.java
  src/main/java/com/daon/onjung/event/domain/service/EventService.java
Labels: ✨ Feature, bianbbc87

#48 ✨ Feature/#9 - 온기를 전한 기업들 조회 API 구현
  http/company/CompanyControllerHttpRequest.http
  src/main/java/com/daon/onjung/company/application/controller/command/CompanyCommandV1Controller.java
  src/main/java/com/daon/onjung/company/application/controller/query/CompanyQueryV1Controller.java
  src/main/java/com/daon/onjung/company/application/dto/request/CreateCompanyRequestDto.java
  src/main/java/com/daon/onjung/company/application/dto/response/ReadCompanyBriefResponseDto.java
  src/main/java/com/daon/onjung/company/application/service/CreateCompanyService.java
  src/main/java/com/daon/onjung/company/application/service/ReadCompanyBriefService.java
  src/main/java/com/daon/onjung/company/application/usecase/CreateCompanyUseCase.java
  src/main/java/com/daon/onjung/company/application/usecase/ReadCompanyBriefUseCase.java
  src/main/java/com/daon/onjung/company/domain/service/CompanyService.java
  src/main/java/com/daon/onjung/company/repository/mysql/CompanyRepository.java
  src/main/java/com/daon/onjung/core/constant/Constants.java
  src/main/java/com/daon/onjung/core/utility/S3Util.java
  src/main/java/com/daon/onjung/security/domain/type/EImageType.java
Labels: ✨ Feature, bianbbc87

#49 ✨ Feature/#11 - 나의 식권 조회 API 구현
  http/Event/EventControllerHttpRequest.http
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/event/application/controller/query/TicketQueryV1Controller.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketResponseDto.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketService.java
  src/main/java/com/daon/onjung/event/application/usecase/ReadTicketUseCase.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
Labels: ✨ Feature, bianbbc87

#55 ✨ Feature/#13 - 식권 유효성 검증 및 사용처리 API 구현
  http/Event/EventControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/constant/Constants.java
  src/main/java/com/daon/onjung/event/application/controller/command/EventCommandV1Controller.java
  src/main/java/com/daon/onjung/event/application/dto/request/ReadTicketValidateRequestDto.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketValidateResponseDto.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketBriefService.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketValidateService.java
  src/main/java/com/daon/onjung/event/application/usecase/ReadTicketValidateUseCase.java
  src/main/java/com/daon/onjung/event/domain/Ticket.java
  src/main/java/com/daon/onjung/event/domain/service/TicketService.java
  src/main/java/com/daon/onjung/security/repository/mysql/AccountRepository.java
Labels: ✨ Feature, bianbbc87

#61 🐞 BugFix/#60 - Store의 Title, Introduction, Name 필드 크기 제한으로 발생한 버그 해결
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/domain/Store.java
Labels: 🐞 BugFix, dongkyeomjang

#63 🔨 Refactor/#62 - OnjungTag Controller 반영
  src/main/java/com/daon/onjung/account/application/controller/query/StoreQueryV1Controller.java
  src/main/java/com/daon/onjung/account/application/service/ReadStoreOverviewService.java
Labels: 🔨 Refactor, bianbbc87

#66 ✨ Feature/#65 - FCM 푸시알림 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/daon/onjung/core/utility/CookieUtil.java
  src/main/java/com/daon/onjung/core/utility/FirebaseUtil.java
  src/main/java/com/daon/onjung/core/utility/HeaderUtil.java
  src/main/java/com/daon/onjung/core/utility/HttpServletUtil.java
  src/main/java/com/daon/onjung/core/utility/PasswordUtil.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
  src/main/java/com/daon/onjung/security/handler/logout/DefaultLogoutSuccessHandler.java
Labels: ✨ Feature, dongkyeomjang

#68 🌏 Deploy/#67 - cicd pipeline에 firebase-key 생성 추가
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy, dongkyeomjang

#70 🌏 Deploy/#69 - cicd pipeline에 firebase-key 생성 추가
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy, dongkyeomjang

#72 🔨 Refactor/#71 - 푸시알림 문구 수정
  src/main/java/com/daon/onjung/core/utility/FirebaseUtil.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
Labels: 🔨 Refactor, dongkyeomjang

#74 🔨 Refactor/#73 - 푸시알림에 JSON 데이터 추가
  src/main/java/com/daon/onjung/core/utility/FirebaseUtil.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/event/domain/Ticket.java
Labels: 🔨 Refactor, dongkyeomjang

#64 🔨 Refactor/#59 - 3.2 가게 상세 정보 조회 store history info 배열로 변경
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/controller/command/StoreCommandV1Controller.java
  src/main/java/com/daon/onjung/account/application/dto/request/CreateStoreHistoryRequestDto.java
  src/main/java/com/daon/onjung/account/application/dto/response/ReadStoreDetailResponseDto.java
  src/main/java/com/daon/onjung/account/application/service/CreateStoreHistoryService.java
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
  src/main/java/com/daon/onjung/account/application/usecase/CreateStoreHistoryUseCase.java
  src/main/java/com/daon/onjung/account/domain/StoreHistory.java
  src/main/java/com/daon/onjung/account/domain/service/StoreHistoryService.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketResponseDto.java
Labels: 🔨 Refactor, bianbbc87

#76 🔨 Refactor/#75 : qr 생성용 이미지 file -> url로 변경
  src/main/java/com/daon/onjung/core/utility/QrUtil.java
Labels: 🔨 Refactor, bianbbc87

#78 🔨 Refactor/#77 - 4.7 동참하기 requestBody 필드에 필요없는 eventId 값 삭제
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/dto/response/ReadStoreDetailResponseDto.java
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
  src/main/java/com/daon/onjung/onjung/application/dto/request/CreateDonationRequestDto.java
  src/main/java/com/daon/onjung/onjung/application/service/CreateDonationService.java
Labels: 🔨 Refactor, dongkyeomjang

#82 ✨ Feature/#81 - 3.5 푸시알림 설정 변경(토글) API 구현
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/controller/command/AccountCommandV1Controller.java
  src/main/java/com/daon/onjung/account/application/controller/query/AccountQueryV1Controller.java
  src/main/java/com/daon/onjung/account/application/dto/response/UpdateUserNotificationAllowedResponseDto.java
  src/main/java/com/daon/onjung/account/application/service/UpdateUserNotificationAllowedService.java
  src/main/java/com/daon/onjung/account/application/usecase/UpdateUserNotificationAllowedUseCase.java
  src/main/java/com/daon/onjung/security/domain/mysql/Account.java
  src/main/java/com/daon/onjung/security/domain/service/AccountService.java
Labels: ✨ Feature, dongkyeomjang

#86 ✨ Feature/#83 - 5.6 보유한 티켓 개수 조회 API 구현
  http/Event/EventControllerHttpRequest.http
  src/main/java/com/daon/onjung/event/application/controller/command/.keep
  src/main/java/com/daon/onjung/event/application/controller/query/.keep
  src/main/java/com/daon/onjung/event/application/controller/query/TicketQueryV1Controller.java
  src/main/java/com/daon/onjung/event/application/dto/.keep
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketCountResponseDto.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketCountService.java
  src/main/java/com/daon/onjung/event/application/usecase/ReadTicketCountUseCase.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
Labels: ✨ Feature, dongkyeomjang

#88 🐞 BugFix/#87 - OCRUtil의 ObjectMapper에 FAIL_ON_UNKNOWN_PROPERTIES인 경우 …
  http/auth/AuthControllerHttpRequest.http
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/dto/ReceiptOCRDto.java
  src/main/java/com/daon/onjung/core/utility/OCRUtil.java
Labels: 🐞 BugFix, dongkyeomjang

#89 ✨ Feature/#16 - 온기 우편함 조회 API 구현
  http/Event/EventControllerHttpRequest.http
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
  src/main/java/com/daon/onjung/company/application/dto/response/ReadCompanyBriefResponseDto.java
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/event/application/controller/query/TicketQueryV1Controller.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadOnjungEventOverviewResponseDto.java
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
  src/main/java/com/daon/onjung/event/application/usecase/ReadOnjungEventOverviewUseCase.java
  src/main/java/com/daon/onjung/event/repository/mysql/EventRepository.java
  src/main/java/com/daon/onjung/onjung/application/controller/query/OnjungQueryV1Controller.java
  src/main/java/com/daon/onjung/onjung/application/dto/response/ReadUserOnjungBriefResponseDto.java
  src/main/java/com/daon/onjung/onjung/application/service/ReadUserOnjungBriefService.java
  src/main/java/com/daon/onjung/onjung/application/usecase/ReadUserOnjungBriefUseCase.java
  src/main/java/com/daon/onjung/onjung/domain/service/OnjungService.java
  src/main/java/com/daon/onjung/onjung/domain/type/EOnjungType.java
Labels: ✨ Feature, bianbbc87

#93 🐞 BugFix/#92 - 온기 상세 조회에서 BankUtil에 조회요청 보낼 시 bankId 대신 storeId를 보내고있던 버그 수정
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
Labels: 🐞 BugFix, dongkyeomjang

#95 🔨 Refactor/#94 - StoreHistory의 amount 형식을 Integer에서 String으로 변경
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/dto/request/CreateStoreHistoryRequestDto.java
  src/main/java/com/daon/onjung/account/application/dto/response/ReadStoreDetailResponseDto.java
  src/main/java/com/daon/onjung/account/domain/StoreHistory.java
  src/main/java/com/daon/onjung/account/domain/service/StoreHistoryService.java
Labels: 🔨 Refactor, dongkyeomjang

#97 🔨 Refactor/#96 - 4.8 함께한 식당 조회하기 Response에 store_id, logo_img_url 추가
  src/main/java/com/daon/onjung/account/domain/StoreHistory.java
  src/main/java/com/daon/onjung/onjung/application/dto/response/ReadUserOnjungOverviewResponseDto.java
Labels: 🔨 Refactor, dongkyeomjang

#99 🔨 Refactor/#98 - Store 상세조회 시 StoreHistory 그룹 밖, 그룹 안 시간순 정렬 추가
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
Labels: 🔨 Refactor, dongkyeomjang

#101 🔨 Refactor/#100 - 사용자 정보 조회에 notification_allowed 필드 추가
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/daon/onjung/account/application/controller/query/AccountQueryV1Controller.java
  src/main/java/com/daon/onjung/account/application/dto/response/ReadUserOverviewsResponseDto.java
  src/main/java/com/daon/onjung/account/application/service/ReadUserOverviewService.java
  src/main/java/com/daon/onjung/account/application/usecase/ReadUserOverviewUseCase.java
Labels: 🔨 Refactor, dongkyeomjang

#103 🐞 BugFix/#102 - 잘못된 JOIN 사용으로 인한, 가게 상세조회 시 Donator Count가 제대로 구해지지 않…
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
Labels: 🐞 BugFix, dongkyeomjang

#105 ✨ Feature - 스케줄러의 Job을 Redis로 관리하는 기능 추가
  http/DummyHttpRequest.http
  http/account/AccountControllerHttpRequest.http
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/daon/onjung/OnjungMainServerApplication.java
  src/main/java/com/daon/onjung/core/config/SchedulerConfig.java
  src/main/java/com/daon/onjung/core/domain/ScheduledEventJob.java
  src/main/java/com/daon/onjung/core/domain/service/ScheduledEventJobService.java
  src/main/java/com/daon/onjung/core/listener/AppEventListener.java
  src/main/java/com/daon/onjung/core/listener/SchedulerRecoveryListener.java
  src/main/java/com/daon/onjung/core/repository/redis/ScheduledEventJobRepository.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/event/domain/event/EventScheduled.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
Labels: ✨ Feature, dongkyeomjang

#107 🔨 Refactor/#106 - 온기우편함에 storeId 추가
  src/main/java/com/daon/onjung/event/application/dto/response/ReadOnjungEventOverviewResponseDto.java
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
Labels: 🔨 Refactor, dongkyeomjang

#109 🐞 BugFix/#108 - Scheduled Job이 empty일때의 버그
  src/main/java/com/daon/onjung/core/listener/SchedulerRecoveryListener.java
Labels: 🐞 BugFix, dongkyeomjang

#111 🐞 BugFix/#108 - Job NullPointException 해결
  src/main/java/com/daon/onjung/core/listener/SchedulerRecoveryListener.java
Labels: 🐞 BugFix, dongkyeomjang

#114 🔨 Refactor/#113 : 온기 우편함 event repo 조회 list로 조회 후 하나만 반환
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
  src/main/java/com/daon/onjung/event/repository/mysql/EventRepository.java
Labels: 🔨 Refactor, bianbbc87

#116 🔨 Refactor/#115 - Redis TTL 수정(14일)
  src/main/java/com/daon/onjung/core/domain/ScheduledEventJob.java
Labels: 🔨 Refactor, dongkyeomjang

#118 🔨 Refactor/#117 - 이벤트 Consume 로직에 Job 삭제 로직 추가
  src/main/java/com/daon/onjung/core/domain/ScheduledEventJob.java
  src/main/java/com/daon/onjung/event/application/controller/consumer/EventSchedulerConsumerV1Controller.java
Labels: 🔨 Refactor, dongkyeomjang

#120 🐞 BugFix/#119 - deleteById -> deleteByEventId 오타 수정
  src/main/java/com/daon/onjung/core/repository/redis/ScheduledEventJobRepository.java
  src/main/java/com/daon/onjung/event/application/controller/consumer/EventSchedulerConsumerV1Controller.java
Labels: 🐞 BugFix, dongkyeomjang

#122 🐞 BugFix/#121 - Spring Data Redis는 기본 키(@Id) 기반 삭제만 지원해서 발생하는 버그
  src/main/java/com/daon/onjung/core/repository/redis/ScheduledEventJobRepository.java
  src/main/java/com/daon/onjung/event/application/controller/consumer/EventSchedulerConsumerV1Controller.java
Labels: 🐞 BugFix, dongkyeomjang

#126 🔨 Refactor/#125 - 4.7 날짜 형식 변경
  src/main/java/com/daon/onjung/onjung/application/dto/response/CreateDonationResponseDto.java
Labels: 🔨 Refactor, dongkyeomjang

#127 🔨 Refactor/#123 - 페이지네이션 코드 수정
  src/main/java/com/daon/onjung/account/application/service/ReadStoreOverviewService.java
  src/main/java/com/daon/onjung/account/repository/mysql/StoreRepository.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketService.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
Labels: 🔨 Refactor, bianbbc87

#128 🔨 Refactor/#124 - ResponseDTO validation 추가
  src/main/java/com/daon/onjung/event/application/dto/response/ReadOnjungEventOverviewResponseDto.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketBriefResponseDto.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketResponseDto.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketValidateResponseDto.java
Labels: 🔨 Refactor, bianbbc87

#138 🔨 Refactor/#137 3.2 가게 상세 정보 조회 가게 히스토리 ASC -> DESC로 변경
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
  src/main/java/com/daon/onjung/account/repository/mysql/StoreHistoryRepository.java
Labels: 🔨 Refactor, bianbbc87

#140 🔨 Refactor/#139 - 온기 우편함, 티켓조회 ASC -> DESC로 변경
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketService.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
  src/main/java/com/daon/onjung/onjung/domain/service/OnjungService.java
Labels: 🔨 Refactor, bianbbc87

#142 🐞 BugFix/#141 - OCR 날짜 파싱 버그 & 영수증 생성날짜를 방문날짜 대신 주고있던 버그 수정
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
Labels: 🐞 BugFix, dongkyeomjang

#144 🔨 Refactor/#143 - 가게 상세 조회, 온기 우편함, 식권 조회 정렬 변경
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
  src/main/java/com/daon/onjung/account/repository/mysql/StoreHistoryRepository.java
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketService.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
Labels: 🔨 Refactor, bianbbc87

#150 ✨ Feature/#149 - 사용한 식권 맨 아래로 정렬
  src/main/java/com/daon/onjung/event/application/service/ReadTicketService.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
Labels: ✨ Feature, dongkyeomjang

#152 🔨 Refactor/#151 - core에 있는 domain, repository을 event로 이동
  src/main/java/com/daon/onjung/account/application/service/ReadStoreDetailService.java
  src/main/java/com/daon/onjung/account/domain/Store.java
  src/main/java/com/daon/onjung/core/listener/AppEventListener.java
  src/main/java/com/daon/onjung/core/listener/SchedulerRecoveryListener.java
  src/main/java/com/daon/onjung/event/application/controller/consumer/EventSchedulerConsumerV1Controller.java
  src/main/java/com/daon/onjung/event/application/dto/response/ReadTicketResponseDto.java
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/event/application/service/ReadOnjungEventOverviewService.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketService.java
  src/main/java/com/daon/onjung/event/application/service/ReadTicketValidateService.java
  src/main/java/com/daon/onjung/event/domain/mysql/Event.java
  src/main/java/com/daon/onjung/event/domain/mysql/Ticket.java
  src/main/java/com/daon/onjung/event/domain/redis/ScheduledEventJob.java
  src/main/java/com/daon/onjung/event/domain/service/EventService.java
  src/main/java/com/daon/onjung/event/domain/service/ScheduledEventJobService.java
  src/main/java/com/daon/onjung/event/domain/service/TicketService.java
  src/main/java/com/daon/onjung/event/repository/mysql/EventRepository.java
  src/main/java/com/daon/onjung/event/repository/mysql/TicketRepository.java
  src/main/java/com/daon/onjung/event/repository/redis/ScheduledEventJobRepository.java
  src/main/java/com/daon/onjung/onjung/application/service/CreateDonationService.java
  src/main/java/com/daon/onjung/onjung/domain/Donation.java
  src/main/java/com/daon/onjung/onjung/domain/service/DonationService.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
  src/main/java/com/daon/onjung/security/repository/mysql/AccountRepository.java
Labels: 🔨 Refactor, dongkyeomjang

#91 📝 docs/#43 : readme 추가
  README.md
Labels: 📃 Docs, bianbbc87

#154 🔨 Refactor/#153 - Notification Data 필드에 title, body 추가
  src/main/java/com/daon/onjung/core/utility/FirebaseUtil.java
Labels: 🔨 Refactor, dongkyeomjang

#160 ✨ Feature/#159 - 6.1 게시글 리스트 조회 API 구현
  http/suggestion/SuggestionControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/utility/DateTimeUtil.java
  src/main/java/com/daon/onjung/suggestion/application/controller/query/SuggestionQueryV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/.keep
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardOverviewResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/.keep
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardOverviewService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/.keep
  src/main/java/com/daon/onjung/suggestion/application/usecase/ReadBoardOverviewUseCase.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/BoardRepository.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/CommentRepository.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/LikeRepository.java
Labels: ✨ Feature, dongkyeomjang

#162 ✨ Feature/#161 - 6.2 게시글 상세 조회 API 구현
  http/suggestion/SuggestionControllerHttpRequest.http
  src/main/java/com/daon/onjung/suggestion/application/controller/query/SuggestionQueryV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardDetailResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardDetailService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/ReadBoardDetailUseCase.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/LikeRepository.java
Labels: ✨ Feature, dongkyeomjang

#164 ✨ Feature/#163 - 6.3 댓글 리스트 조회 API 구현
  http/suggestion/SuggestionControllerHttpRequest.http
  src/main/java/com/daon/onjung/suggestion/application/controller/query/SuggestionQueryV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadCommentOverviewResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadCommentOverviewService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/ReadCommentOverviewUseCase.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/CommentRepository.java
Labels: ✨ Feature, dongkyeomjang

#166 🔨 Refactor/#165 - 6.2 게시글 상세보기에, 내가 쓴 글인지 여부 의미하는 is_me 필드 추가
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardDetailResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardDetailService.java
Labels: 🔨 Refactor, dongkyeomjang

#168 ✨ Feature/#167 - 6.4 게시글 작성 API 구현
  http/suggestion/SuggestionControllerHttpRequest.http
  src/main/java/com/daon/onjung/core/utility/S3Util.java
  src/main/java/com/daon/onjung/security/domain/type/EImageType.java
  src/main/java/com/daon/onjung/suggestion/application/dto/request/.keep
  src/main/java/com/daon/onjung/suggestion/application/dto/request/CreateBoardRequestDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateBoardService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateBoardUseCase.java
  src/main/java/com/daon/onjung/suggestion/domain/Board.java
  src/main/java/com/daon/onjung/suggestion/domain/service/BoardService.java
Labels: ✨ Feature, dongkyeomjang

#170 ✨ Feature/#169 - 6.5 댓글 작성 API 구현
  http/suggestion/SuggestionControllerHttpRequest.http
  src/main/java/com/daon/onjung/suggestion/application/controller/command/SuggestionCommandV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/dto/request/CreateCommentRequestDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateCommentService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateCommentUseCase.java
  src/main/java/com/daon/onjung/suggestion/domain/service/CommentService.java
Labels: ✨ Feature, dongkyeomjang

#172 ✨ Feature/#171 - 6.6 게시글 좋아요 API 구현
  http/suggestion/SuggestionControllerHttpRequest.http
  src/main/java/com/daon/onjung/suggestion/application/controller/command/.keep
  src/main/java/com/daon/onjung/suggestion/application/controller/command/SuggestionCommandV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateOrDeleteLikeService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateOrDeleteLikeUseCase.java
  src/main/java/com/daon/onjung/suggestion/domain/service/LikeService.java
  src/main/java/com/daon/onjung/suggestion/repository/mysql/LikeRepository.java
Labels: ✨ Feature, dongkyeomjang

#174 🔨 Refactor/#173 - 좋아요 수와 댓글 수를 Board의 필드로 추가 및, 필드에서 값 읽어오도록 로직 변경
  http/ConcurrencyIssueTestHttpRequest.http
  http/ConcurrencyIssueTestHttpRequest2.http
  http/onjung/OnjungControllerHttpRequest.http
  src/main/java/com/daon/onjung/suggestion/application/controller/query/.keep
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardDetailResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/ReadBoardOverviewResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateCommentService.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateOrDeleteLikeService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardDetailService.java
  src/main/java/com/daon/onjung/suggestion/application/service/ReadBoardOverviewService.java
  src/main/java/com/daon/onjung/suggestion/domain/Board.java
  src/main/java/com/daon/onjung/suggestion/domain/service/BoardService.java
Labels: 🔨 Refactor, dongkyeomjang

#176 🐞 BugFix - RabbitMQ와 Optimistic Lock을 이용한 동시성 문제 해결
  build.gradle
  src/main/java/com/daon/onjung/core/config/RabbitMQConfig.java
  src/main/java/com/daon/onjung/core/exception/error/ErrorCode.java
  src/main/java/com/daon/onjung/suggestion/application/controller/command/SuggestionCommandV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/CommentV1Consumer.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/LikeV1Consumer.java
  src/main/java/com/daon/onjung/suggestion/application/controller/producer/CommentV1Producer.java
  src/main/java/com/daon/onjung/suggestion/application/controller/producer/LikeV1Producer.java
  src/main/java/com/daon/onjung/suggestion/application/dto/request/CommentMessage.java
  src/main/java/com/daon/onjung/suggestion/application/dto/request/LikeMessage.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateCommentService.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateOrDeleteLikeService.java
  src/main/java/com/daon/onjung/suggestion/application/service/SendCommentRequestService.java
  src/main/java/com/daon/onjung/suggestion/application/service/SendLikeRequestService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateOrDeleteLikeUseCase.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/SendCommentRequestUseCase.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/SendLikeRequestUseCase.java
  src/main/java/com/daon/onjung/suggestion/domain/Board.java
Labels: 🐞 BugFix, dongkyeomjang

#178 🔨 Refactor/#177 - RabbitMQ의 RPC 요청-응답 패턴을 사용하여 댓글 및 좋아요 생성 시, ResponseBody 반환하게 변경
  src/main/java/com/daon/onjung/core/config/RabbitMQConfig.java
  src/main/java/com/daon/onjung/suggestion/application/controller/command/SuggestionCommandV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/CommentV1Consumer.java
  src/main/java/com/daon/onjung/suggestion/application/controller/consumer/LikeV1Consumer.java
  src/main/java/com/daon/onjung/suggestion/application/controller/producer/CommentV1Producer.java
  src/main/java/com/daon/onjung/suggestion/application/controller/producer/LikeV1Producer.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/CreateCommentResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/CreateOrDeleteLikeResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateCommentService.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateOrDeleteLikeService.java
  src/main/java/com/daon/onjung/suggestion/application/service/SendCommentRequestService.java
  src/main/java/com/daon/onjung/suggestion/application/service/SendLikeRequestService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateCommentUseCase.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateOrDeleteLikeUseCase.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/SendCommentRequestUseCase.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/SendLikeRequestUseCase.java
Labels: 🔨 Refactor, dongkyeomjang

#180 🔨 Refactor/#179 - 게시글 생성 시 생성된 게시글 id 함께 반환
  src/main/java/com/daon/onjung/event/application/service/ProcessCompletedEventService.java
  src/main/java/com/daon/onjung/security/application/service/SignUpOwnerByDefaultService.java
  src/main/java/com/daon/onjung/suggestion/application/controller/command/SuggestionCommandV1Controller.java
  src/main/java/com/daon/onjung/suggestion/application/dto/response/CreateBoardResponseDto.java
  src/main/java/com/daon/onjung/suggestion/application/service/CreateBoardService.java
  src/main/java/com/daon/onjung/suggestion/application/usecase/CreateBoardUseCase.java
Labels: 🔨 Refactor, dongkyeomjang

#182 🐞 BugFix/#181 - postAt -> postAgo 오타 수정
  src/main/java/com/daon/onjung/suggestion/application/dto/response/CreateCommentResponseDto.java
Labels: 🐞 BugFix, dongkyeomjang

#184 🔨 Refactor/#183 - 카카오 프로필 이미지 url 가공
  src/main/java/com/daon/onjung/account/domain/service/UserService.java
Labels: 🔨 Refactor, dongkyeomjang
